sudo apt install git python2

sudo apt install python2 -m pip install tqdm

sudo apt install python2 -m pip install colorama

https://github.com/palahsu/Finding-cPaneladminofWebsite

cd Finding-cPaneladminofWebsite

python2 -m pip install -r administrator.txt

ls

python2 findingadmin.py
